### ISSUE TITLE
Typo in the official docs

### ISSUE THREAD

**Issue by mikolaszko** [resendlabs/resend-laravel#29]
Hi!
I recently integrated Resend into my PaaS and it works like a charm - thanks for such an accessible DX. 
I noticed just one thing because it gave me a little bit of an headache - in the official docs for laravel under this url: https://resend.com/docs/send-with-laravel in the "Using the Resend Facade" section there's a typo in the class' method. 
Resend::emails() is the correct syntax and on the website we can see a Resend::email() which results in a laravel error. 
I dont know if its the right place to report this minor issue - if its not then please let me know so I can go and let the right person know :D 

Once again, thanks for such a great laravel integration even if it's a niche

**Comment by jayanratna** [comment]
Thank you for reporting this. Im glad you like the integration.

This is definitely the right place for an issue like this. I'll get that fixed ASAP.

**Comment by jayanratna** [comment]
We've updated the docs: https://resend.com/docs/send-with-laravel

Once again thanks for reporting this ❤️
