### ISSUE TITLE
Sending to multiple recipients fails

### ISSUE THREAD

**Issue by mjadczak** [resendlabs/resend-laravel#30]
When specifying multiple recipients, sending fails with a 422 error.
This is because the library is imploding the recipients using a comma, but actually Resend docs specify that multiple recipients should be specified using an array: https://resend.com/docs/api-reference/emails/send-email

**Comment by jayanratna** [comment]
You're absolutely right here. Thank you for catching this.

This should be an array of strings. The same would apply for the `cc` & `bcc` parameters. I'll get a fix out for this ASAP.
