### ISSUE TITLE
Unsupported mail transport [resend].

### ISSUE THREAD

**Issue by marijnbent** [resendlabs/resend-laravel#44]
Not sure what I miss.. 

Error:
<img width="911" alt="image" src="https://github.com/resendlabs/resend-laravel/assets/11903095/c02558ae-dcc8-4ecd-9c29-e60cc8695556">

mail.php
```php
    'mailers' => [
        'resend' => [
            'transport' => 'resend',
        ],
        'smtp' => [
            'transport' => 'smtp',
            'url' => env('MAIL_URL'),
            'host' => env('MAIL_HOST', 'smtp.mailgun.org'),
            'port' => env('MAIL_PORT', 587),
            'encryption' => env('MAIL_ENCRYPTION', 'tls'),
            'username' => env('MAIL_USERNAME'),
            'password' => env('MAIL_PASSWORD'),
            'timeout' => null,
            'local_domain' => env('MAIL_EHLO_DOMAIN'),
        ],

        'ses' => [
            'transport' => 'ses',
        ],
...
```

.env:
<img width="461" alt="image" src="https://github.com/resendlabs/resend-laravel/assets/11903095/a3e79895-15fb-4b90-9ccd-66ce47112800">

composer:
<img width="693" alt="image" src="https://github.com/resendlabs/resend-laravel/assets/11903095/601ac36e-407a-4616-948a-207ae911bef7">

**Comment by jayanratna** [comment]
Hey @marijnbent, your config looks correct to me. Perhaps your config is cached?

You can create a new cache using `php artisan config:cache` or you can clear it using `php artisan config:clear`

Let me know how you go with this.

**Comment by marijnbent** [comment]
Probably something like that :-). Today, it worked without problem. Thanks!
